services:
  ceph-mon:
    container_name: ceph-mon
    restart: always
    image: ceph/daemon
    command: ["mon"]
    environment:
      MON_IP: 192.168.55.2
      CEPH_PUBLIC_NETWORK: 192.168.55.0/24
    volumes:
      - ./data/ceph_conf:/etc/ceph
      - ./data/ceph_data:/var/lib/ceph
      - ./credential:/credential

    networks:
      ceph-net:
        ipv4_address: "192.168.55.2"

  ceph-mgr:
    container_name: ceph-mgr
    image: ceph/daemon
    command: ["mgr"]
    volumes:
      - ./data/ceph_conf:/etc/ceph
      - ./data/ceph_data:/var/lib/ceph
    depends_on:
      - ceph-mon
    networks:
      ceph-net:
        ipv4_address: "192.168.55.3"
    ports:
      - 8443:8443

  ceph-osd1:
    pid: host
    privileged: true
    container_name: ceph-osd1
    image: ceph/daemon
    command: ["osd_directory"]
    volumes:
      - ./data/ceph_conf:/etc/ceph
      - ./data/ceph_data:/var/lib/ceph
      - ./data/ceph_data/osds/osd1:/var/lib/ceph/osd
    depends_on:
      - ceph-mon
    networks:
      ceph-net:
        ipv4_address: "192.168.55.4"

  ceph-osd2:
    pid: host
    privileged: true
    container_name: ceph-osd2
    image: ceph/daemon
    command: ["osd_directory"]
    volumes:
      - ./data/ceph_conf:/etc/ceph
      - ./data/ceph_data:/var/lib/ceph
      - ./data/ceph_data/osds/osd2:/var/lib/ceph/osd
    depends_on:
      - ceph-mon
    networks:
      ceph-net:
        ipv4_address: "192.168.55.5"

  ceph-osd3:
    pid: host
    privileged: true
    container_name: ceph-osd3
    image: ceph/daemon
    command: ["osd_directory"]
    volumes:
      - ./data/ceph_conf:/etc/ceph
      - ./data/ceph_data:/var/lib/ceph
      - ./data/ceph_data/osds/osd3:/var/lib/ceph/osd
    depends_on:
      - ceph-mon
    networks:
      ceph-net:
        ipv4_address: "192.168.55.6"

  ceph-rgw:
    container_name: ceph-rgw
    image: ceph/daemon
    command: ["rgw"]
    volumes:
      - ./data/ceph_conf:/etc/ceph
      - ./data/ceph_data:/var/lib/ceph
    depends_on:
      - ceph-osd1
      - ceph-osd2
      - ceph-osd3
    networks:
      ceph-net:
        ipv4_address: "192.168.55.7"
    ports:
      - 7480:7480

  ceph-mds:
    image: ceph/daemon
    command: ["mds"]
    hostname: ceph-mds
    container_name: ceph-mds
    environment:
      CEPHFS_CREATE: 1
    volumes:
      - ./data/ceph_conf:/etc/ceph
      - ./data/ceph_data:/var/lib/ceph
    depends_on:
      - ceph-osd1
      - ceph-osd2
      - ceph-osd3
    networks:
      ceph-net:
        ipv4_address: "192.168.55.8"

networks:
  ceph-net:
    ipam:
      driver: default
      config:
        - subnet: 192.168.55.0/24
  app-network:
    driver: bridge
    external: true
  sabay_docker:
    external: true